#!/bin/bash
shopt -s extglob;

find_context ()
{
	linenum=$(echo $1 | awk -F: '{printf "%s", $2}')
	filename=$(echo $1 | awk -F: '{printf "%s", $1}')
	if [[ $linenum -lt 10 ]]; then
		head -n $linenum "$filename"
	elif [[ $linenum -gt $(wc -l <"$filename") ]]; then
		tail -n $(($(wc -l <"$filename") - $linenum))
	else
		range1=$(($linenum - 10))
		range2=$(($linenum + 10))
		sed -n "$range1","$range2"p "$filename"
	fi
}


[ -x /usr/bin/sw ] && swallowthis="sw"
item=$(xclip -o -selection primary)
full_path="$1/$item"
dir_p=1

case $item in
    *\.jpg | *\.png)
        sel=$(printf "sxiv\npage\nfeh" | 91menu)
        [ "$sel" = "sxiv" ] && $swallowthis firejail sxiv -ap "$full_path" &>/dev/null
        [ "$sel" = "page" ] && $swallowthis firejail page "$full_path" &>/dev/null
        [ "$sel" = "feh" ] && $swallowthis firejail feh "$full_path" &>/dev/null
        ;;
    *\.mp4 | *\.webm | *\.mov | *\.mkv | *\.gif | *\.mp3)
        sel=$(printf "mpv\n" | 91menu)
        [ "$sel" = "mpv" ] && $swallowthis mpv "$full_path" &>/dev/null
        ;;
    *\.pdf | *\.epub)
        sel=$(printf "zathura\nmupdf" | 91menu)
        [ "$sel" = "zathura" ] && $swallowthis zathura "$full_path" &>/dev/null
        [ "$sel" = "mupdf" ] && $swallowthis mupdf "$full_path" &>/dev/null
        ;;
	*\.htm?(l) | *\.css)
		sel=$(printf "firefox\nchromium\nedit" | 91menu)
		[ "$sel" = "firefox" ] && $swallowthis librewolf "$full_path" &>/dev/null
		[ "$sel" = "chromium" ] && $swallowthis chromium "$full_path" &>/dev/null
		[ "$sel" = "edit" ] && $swallowthis emacsclient -c "$full_path" &>/dev/null
		;;
	http?(s)://*)
		sel=$(printf "firefox\nchrome" | 91menu)
		[ "$sel" = "firefox" ] && $swallowthis librewolf "$item" &>/dev/null
		[ "$sel" = "chrome" ] && $swallowthis chromium "$item" &>/dev/null
		;;
	+([[:ascii:]])\.+([a-zA-Z]))
		sel=$(printf "emacs\nvim\nacme" | 91menu)
		[ "$sel" = "emacs" ] && $swallowthis emacsclient -c "$full_path"
		[ "$sel" = "vim" ] && $swallowthis xterm -e vim "$full_path" &>/dev/null
		[ "$sel" = "acme" ] && $swallowthis acme-start.sh "$full_path"
		;;
	+([[:ascii:]]):+([0-9]):*([0-9])?(:) )
		sel=$(printf "emacs\nvim\nacme\ncontext" | 91menu)
		file=$(echo $item | awk -F: '{print $1}')
		linenum=$(echo $item | awk -F: '{print $2}')
		full_path="$1/$file"
		[ "$sel" = "emacs" ] && $swallowthis emacsclient -c +$linenum "$full_path"
		[ "$sel" = "vim" ] && $swallowthis xterm -e vim +$linenum "$full_path"
		[ "$sel" = "acme" ] && $swallowthis acme-start.sh "$full_path":$linenum
		[ "$sel" = "context" ] && find_context "$item"
		;;
    *)
		if [[ -d "$full_path" ]]; then
			dir_p=0
		else
			if [[ $(file --mime-type "$full_path" | cut -d ' ' -f 2 | cut -d \/ -f 1) == "text" ]]; then
				$swallowthis emacsclient -c "$full_path"
			else
				echo "Could not plumb"
			fi
		fi
		;;
esac

exit $dir_p
