#!/bin/bash
shopt -s extglob;

find_context ()
{
	linenum=$(echo $1 | awk -F: '{printf "%s", $2}')
	filename=$(echo $1 | awk -F: '{printf "%s", $1}')
	if [[ $linenum -lt 10 ]]; then
		head -n $linenum "$filename"
	elif [[ $linenum -gt $(wc -l <"$filename") ]]; then
		tail -n $(($(wc -l <"$filename") - $linenum))
	else
		range1=$(($linenum - 10))
		range2=$(($linenum + 10))
		sed -n "$range1","$range2"p "$filename"
	fi
}

if [ -x /usr/bin/sw ]; then
	swallowthis="sw"
else
	swallowthis=""
fi

item=$(xclip -o -selection primary)
full_path="$1/$item"
dir_p=1

case $item in
    *\.jpg | *\.png)
        sel=$(printf "sxiv\npage\nfeh" | 91menu)
        [ "$sel" = "sxiv" ] && $swallowthis firejail sxiv -ap "$full_path" &>/dev/null
        [ "$sel" = "page" ] && $swallowthis firejail page "$full_path" &>/dev/null
        [ "$sel" = "feh" ] && $swallowthis firejail feh "$full_path" &>/dev/null
        ;;
    *\.mp4 | *\.webm | *\.mov | *\.mkv | *\.gif | *\.mp3)
        sel=$(printf "mpv\n" | 91menu)
        [ "$sel" = "mpv" ] && $swallowthis mpv "$full_path" &>/dev/null
        ;;
    *\.pdf | *\.epub)
        sel=$(printf "zathura\nmupdf" | 91menu)
        [ "$sel" = "zathura" ] && $swallowthis zathura "$full_path" &>/dev/null
        [ "$sel" = "mupdf" ] && $swallowthis mupdf "$full_path" &>/dev/null
        ;;
	*\.html | *\.css)
		sel=$(printf "firefox\nchromium\nedit" | 91menu)
		[ "$sel" = "firefox" ] && $swallowthis librewolf "$full_path"
		[ "$sel" = "chromium" ] && $swallowthis chromium "$full_path"
		[ "$sel" = "edit" ] && $swallowthis emacsclient -c "$full_path"
		;;
	https?(:)//*)
		sel=$(printf "firefox\nchrome" | 91menu)
		[ "$sel" = "firefox" ] && $swallowthis librewolf "$item"
		[ "$sel" = "chrome" ] && $swallowthis chromium "$item"
		;;
	*:+([0-9]):*([0-9])*([:]) )
		sel=$(printf "emacs\nvim\nacme\ncontext" | 91menu)
		file=$(echo $item | awk -F: '{print $1}')
		linenum=$(echo $item | awk -F: '{print $2}')
		full_path=$(find -O3 ./ -name "$file" -type f -print 2>/dev/null | 91menu)
		[ "$sel" = "emacs" ] && $swallowthis emacsclient -c +"$linenum" "$full_path"
		[ "$sel" = "vim" ] && $swallowthis vim +$linenum $full_path
		[ "$sel" = "acme" ] && $swallowthis acme-start.sh $full_path:$linenum
		[ "$sel" = "context" ] && find_context $full_path
		;;
    *)
		if [[ -d "$full_path" ]]; then
			dir_p=0
		else
			$swallowthis emacsclient -c "$full_path"
		fi
		;;
esac

exit $dir_p
