#!/bin/sh

# Usage:
# `$0`: Ask for recording type via dmenu
# `$0 screencast`: Record both audio and screen
# `$0 video`: Record only screen
# `$0 audio`: Record only audio
# `$0 kill`: Kill existing recording
#
# If there is already a running instance, user will be prompted to end it.

video_dir="/home/ken_nc/Videos/recordings"

killrecording() {
	recpid="$(cat /tmp/recordingpid)"
	# kill with SIGTERM, allowing finishing touches.
	kill -15 "$recpid"
	rm -f /tmp/recordingpid
	# even after SIGTERM, ffmpeg may still run, so SIGKILL it.
	sleep 3
	kill -9 "$recpid"
	exit
	}

screencast() { \
  ffmpeg -y \
  -thread_queue_size 32 \
	-f x11grab \
	-framerate 30 \
	-s "$(xdpyinfo | awk '/dimensions/ {print $2;}')" \
	-i "$DISPLAY" \
	-f alsa -i default \
 	-c:v h264 -crf 0 -preset ultrafast -c:a aac \
	"$video_dir/screencast-$(date '+%y%m%d-%H%M-%S').mp4" &
	echo $! > /tmp/recordingpid
}

askrecording() { \
	choice=$(printf "screencast\\nvideo selected" | dmenu -i -p "Select recording style:")
	case "$choice" in
		screencast) screencast;;
		*selected) videoselected;;
	esac
	}

asktoend() { \
	response=$(printf "No\\nYes" | dmenu -i -p "Recording still active. End recording?") &&
	[ "$response" = "Yes" ] &&  killrecording
	}

videoselected()
{
	slop -f "%x %y %w %h" > /tmp/slop
	read -r X Y W H < /tmp/slop
	rm /tmp/slop

  X=$((X/2*2))
  Y=$((Y/2*2))
  W=$((W/2*2))
  H=$((H/2*2))

	ffmpeg -y\
  -thread_queue_size 64 \
	-f x11grab \
  -framerate 30 \
  -video_size "$W"x"$H" \
	-i :0.0+"$X,$Y" \
	-f pulse -ac 2 -ar 48000 -i alsa_output.pci-0000_00_1f.3.analog-stereo.monitor \
	-f pulse -ac 2 -ar 48000 -i alsa_input.pci-0000_00_1f.3.analog-stereo \
 	-vcodec libx264 -preset ultrafast -crf 24 \
  -acodec libmp3lame -ar 48000 -q:a 1 \
	-pix_fmt yuv420p \
  -filter_complex amix=inputs=2 \
	"$video_dir/box-$(date '+%y%m%d-%H%M-%S').mp4" &
	echo $! > /tmp/recordingpid
}

case "$1" in
	screencast) screencast;;
	*selected) videoselected;;
	kill) killrecording;;
	*) ([ -f /tmp/recordingpid ] && asktoend && exit) || askrecording;;
esac
