#!/bin/bash

# Get youtube url
# Check if it is a music video
# If it is check if user wants to keep the video
# Save file with all thumbnail
# Call eyeD3 to edit tags
# Call 91menu with directory options to move the music video to
# Add option to make new directory

playlist_flag=""

help_message (){
	cat <<EOF
USEAGE: youtube [OPTION]
  -h, --help              Print help message
  url                     url of video or playlist
EXAMPLE:
  youtube https://www.youtube.com/watch?v=YRNKjQg6y-c
EOF
}

download_vid (){
	youtube_url="$1"
	if [[ $youtube_url =~ .*list.* ]]; then
		playlist_flag="y"
		read -e -p "Playlist folder name: " folder_name
		mkdir -p "$folder_name"
		cd "$folder_name"
	fi

	read -e -p "Is this a music video? (y/n): " music_video_check

	if [[ $music_video_check == "n" ]]; then
		yt-dlp --yes-playlist \
			   --skip-playlist-after-errors 4 \
			   "$youtube_url"
	else
		read -e -p "Save video? (y/n): " save_video_check
		if [[ $save_video_check == "y" || $save_video_check == "" ]]; then
			yt-dlp --embed-thumbnail \
				   --extract-audio \
				   --audio-format mp3 \
				   --audio-quality 0 \
				   --output '%(title)s-%(uploader)s.%(ext)s' \
				   --yes-playlist \
				   --skip-playlist-after-errors 4 \
				   --keep-video \
				   "$youtube_url"
		else
			yt-dlp --embed-thumbnail \
				   --extract-audio \
				   --audio-format mp3 \
				   --audio-quality 0 \
				   --output '%(title)s-%(uploader)s.%(ext)s' \
				   --yes-playlist \
				   --skip-playlist-after-errors 4 \
				   --no-keep-video \
				   "$youtube_url"
		fi

		if [[ $playlist_flag == "y" ]]; then
			for i in * ; do
				artist_tag="$(echo "$i" | cut -d \- -f 2 | cut -d \. -f 1)"
				title_tag="$(echo "$i" | cut -d \- -f 1)"
				album_tag="idk"

				eyeD3 --title "$title_tag" \
					  --artist "$artist_tag" \
					  --album "$album_tag" "$i"
			done
		else
			mp3_file="$(ls ./ | fzy -p 'Which file: ')"
			title_tag="$(echo "$mp3_file" | cut -d \- -f 1)"
			artist_tag="$(echo "$mp3_file" | cut -d \- -f 2 | cut -d \. -f 1)"
			album_tag="idk"

			eyeD3 --title "$title_tag" \
			      --artist "$artist_tag" \
			      --album "$album_tag" "$mp3_file"
		fi

		read -e -p "Move to ~/Music? (y/n): " move_mp3_check
		if [[ $move_mp3_check == "y" || $move_mp3_check == "" ]]; then
			sel=$(walk ~/Music | sor 'test -d' | fzy -p '> ')
			if [[ $playlist_flag == "y" ]]; then
				mv ./* "$sel/"
				cd ../
				rm -rf "$folder_name"
			else
				mv "$mp3_file" "$sel/"
			fi
		fi
	fi
}

while [[ ! $# == 0 ]]
do
    case "$1" in
        -h | --help)
			help_message
            ;;
        *)
            download_vid "$1"
            ;;
    esac
    shift
done


# Fix that might be useful somethings
# for i in *; do
# artist_tag="$(echo "$i" | cut -d \- -f 1)"
# title_tag="$(echo "$i" | cut -d \- -f 2 | cut -d \. -f 1)"
# album_tag="idk"
# eyeD3 --title "$title_tag" --artist "$artist_tag" --album "$album_tag" "$i"
# done
